
package net.cd.owen.service.productcatalog;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import net.cd.owen.model.Category;
import net.cd.owen.model.Cd;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductCatalogService", targetNamespace = "http://productcatalog.service.owen.cd.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductCatalogService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<net.cd.owen.service.productcatalog.Cd>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductList", targetNamespace = "http://productcatalog.service.owen.cd.net/", className = "net.cd.owen.service.productcatalog.GetProductList")
    @ResponseWrapper(localName = "getProductListResponse", targetNamespace = "http://productcatalog.service.owen.cd.net/", className = "net.cd.owen.service.productcatalog.GetProductListResponse")
    @Action(input = "http://productcatalog.service.owen.cd.net/ProductCatalogService/getProductListRequest", output = "http://productcatalog.service.owen.cd.net/ProductCatalogService/getProductListResponse")
    public List<Cd> getProductList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @return
     *     returns java.util.List<net.cd.owen.service.productcatalog.Category>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCategoryList", targetNamespace = "http://productcatalog.service.owen.cd.net/", className = "net.cd.owen.service.productcatalog.GetCategoryList")
    @ResponseWrapper(localName = "getCategoryListResponse", targetNamespace = "http://productcatalog.service.owen.cd.net/", className = "net.cd.owen.service.productcatalog.GetCategoryListResponse")
    @Action(input = "http://productcatalog.service.owen.cd.net/ProductCatalogService/getCategoryListRequest", output = "http://productcatalog.service.owen.cd.net/ProductCatalogService/getCategoryListResponse")
    public List<Category> getCategoryList();

    /**
     * 
     * @param arg0
     * @return
     *     returns net.cd.owen.service.productcatalog.Cd
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductInfo", targetNamespace = "http://productcatalog.service.owen.cd.net/", className = "net.cd.owen.service.productcatalog.GetProductInfo")
    @ResponseWrapper(localName = "getProductInfoResponse", targetNamespace = "http://productcatalog.service.owen.cd.net/", className = "net.cd.owen.service.productcatalog.GetProductInfoResponse")
    @Action(input = "http://productcatalog.service.owen.cd.net/ProductCatalogService/getProductInfoRequest", output = "http://productcatalog.service.owen.cd.net/ProductCatalogService/getProductInfoResponse")
    public Cd getProductInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

}
