
package net.cd.owen.service.orderprocess;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderProcessServiceImpService", targetNamespace = "http://orderprocess.service.owen.cd.net/", wsdlLocation = "http://127.0.0.1:8080/cdshop_server/OrderProcessWs?wsdl")
public class OrderProcessServiceImpService
    extends Service
{

    private final static URL ORDERPROCESSSERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORDERPROCESSSERVICEIMPSERVICE_EXCEPTION;
    private final static QName ORDERPROCESSSERVICEIMPSERVICE_QNAME = new QName("http://orderprocess.service.owen.cd.net/", "OrderProcessServiceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/cdshop_server/OrderProcessWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERPROCESSSERVICEIMPSERVICE_WSDL_LOCATION = url;
        ORDERPROCESSSERVICEIMPSERVICE_EXCEPTION = e;
    }

    public OrderProcessServiceImpService() {
        super(__getWsdlLocation(), ORDERPROCESSSERVICEIMPSERVICE_QNAME);
    }

    public OrderProcessServiceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERPROCESSSERVICEIMPSERVICE_QNAME, features);
    }

    public OrderProcessServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, ORDERPROCESSSERVICEIMPSERVICE_QNAME);
    }

    public OrderProcessServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERPROCESSSERVICEIMPSERVICE_QNAME, features);
    }

    public OrderProcessServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderProcessServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderProcessService
     */
    @WebEndpoint(name = "OrderProcessServiceImpPort")
    public OrderProcessService getOrderProcessServiceImpPort() {
        return super.getPort(new QName("http://orderprocess.service.owen.cd.net/", "OrderProcessServiceImpPort"), OrderProcessService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderProcessService
     */
    @WebEndpoint(name = "OrderProcessServiceImpPort")
    public OrderProcessService getOrderProcessServiceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://orderprocess.service.owen.cd.net/", "OrderProcessServiceImpPort"), OrderProcessService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERPROCESSSERVICEIMPSERVICE_EXCEPTION!= null) {
            throw ORDERPROCESSSERVICEIMPSERVICE_EXCEPTION;
        }
        return ORDERPROCESSSERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
