
package net.cd.owen.service.orderprocess;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import net.cd.owen.model.OrderDetail;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderProcessService", targetNamespace = "http://orderprocess.service.owen.cd.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderProcessService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmOrder", targetNamespace = "http://orderprocess.service.owen.cd.net/", className = "net.cd.owen.service.orderprocess.ConfirmOrder")
    @ResponseWrapper(localName = "confirmOrderResponse", targetNamespace = "http://orderprocess.service.owen.cd.net/", className = "net.cd.owen.service.orderprocess.ConfirmOrderResponse")
    @Action(input = "http://orderprocess.service.owen.cd.net/OrderProcessService/confirmOrderRequest", output = "http://orderprocess.service.owen.cd.net/OrderProcessService/confirmOrderResponse")
    public boolean confirmOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveOrder", targetNamespace = "http://orderprocess.service.owen.cd.net/", className = "net.cd.owen.service.orderprocess.SaveOrder")
    @ResponseWrapper(localName = "saveOrderResponse", targetNamespace = "http://orderprocess.service.owen.cd.net/", className = "net.cd.owen.service.orderprocess.SaveOrderResponse")
    @Action(input = "http://orderprocess.service.owen.cd.net/OrderProcessService/saveOrderRequest", output = "http://orderprocess.service.owen.cd.net/OrderProcessService/saveOrderResponse")
    public long saveOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<OrderDetail> arg1);

}
